language: objective-c
osx_image: xcode8
notifications:
  email: false
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=AdaptiveSpaceItem.xcworkspace
  - MACOS_FRAMEWORK_SCHEME="AdaptiveSpaceItem"
  - MACOS_SDK=macosx10.12
  - EXAMPLE_SCHEME="AdaptiveSpaceItem Demo"
  matrix:
    - DESTINATION="arch=x86_64"   SCHEME="$MACOS_FRAMEWORK_SCHEME"   SDK="$MACOS_SDK"  BUILD_EXAMPLE="YES"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Example in Debug if specified
  - if [ $BUILD_EXAMPLE == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi
